name: neuro_ocr
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - opencv
  - matplotlib
  - scikit-learn
  - numpy
  - pip
  - pip:
    - qdrant-client
    - tqdm